## libraries
library(psych)
library(ggplot2)
library(ggpubr)
library(GGally)
library(ROCR)

## Data loading and prep

levallois_data = read.csv("Data/Levallois_flake_data_CORRECTED_v5.csv")
#levallois_data = read.csv("Data/Levallois_flake_data.csv")
levallois_data$SpCode = 0
levallois_data[which(levallois_data$Site == "Tor Faraj"),"SpCode"] <- 1 #Neanderthal
levallois_data[which(levallois_data$Site == "Kebara X"),"SpCode"] <- 1 #Neanderthal
levallois_data[which(levallois_data$Site == "Ksar Akil 28A"),"SpCode"] <- 1 #Neanderthal
levallois_data[which(levallois_data$Site == "JKF-1"),"SpCode"] <- 2 #unknown
levallois_data[which(levallois_data$Site == "ALM-3"),"SpCode"] <- 2

levallois_data[which(levallois_data$SpCode == 0),"Sp"] <- "sapiens"
levallois_data[which(levallois_data$SpCode == 1),"Sp"] <- "neanderthal"
levallois_data[which(levallois_data$SpCode == 2),"Sp"] <- "unknown"

levallois_nona = levallois_data[-which(apply(levallois_data, 1, function(x)any(is.na(x)))),]

var_cols = 3:10

## distributions of raw measurements

plotList <- list()
df <- subset(levallois_nona, Sp != "unknown")
n <- nrow(df)
nbins <- 1 + (3.222 * log(n))
formatted_labels <- c("Number of Scars",
                     "Length",
                     "Proximal Width",
                     "Medial Width",
                     "Distal Width",
                     "Thickness at Medial",
                     "Platform Width",
                     "Platform Thickness")
for(j in 1:8){
   column_name <- names(levallois_nona)[j + 2]
   plotList[[j]] <- ggplot(data=df,mapping=aes_string(x=column_name)) +
                  geom_histogram(mapping=aes_string(y="..count..", fill="Sp"),
                                 bins=nbins,
                                 colour=NA,
                                 alpha=0.5,
                                 position="identity") +
                  labs(x=formatted_labels[j]) +
                  theme_minimal() +
                  theme(text = element_text(family="Times", size=12),
                        plot.title = element_text(face="bold",hjust=0.5,size=15),
                        axis.title.y = element_blank(),
                        axis.text.y = element_blank())
}
ggarrange(plotlist=plotList,
         ncol=4,
         nrow=2,
         common.legend=1)

ggsave(filename="./Images/lithic_measures.pdf",
      device = "pdf")


## pre pca
KMO(levallois_nona[,var_cols])

## run pca
## separate out training data

scaled_vars = apply(levallois_nona[, var_cols], 2, scale)

levallois_nona[, var_cols] <- scaled_vars

unknown_sp <- which(levallois_nona$SpCode==2)

pca_levallois_train = prcomp(levallois_nona[-unknown_sp,var_cols], retx = T, scale = F, center = F)

unknown_proj = as.matrix(levallois_nona[unknown_sp,var_cols]) %*% pca_levallois_train$rotation

unknown_proj = cbind(levallois_nona[unknown_sp,], unknown_proj)

levallois_proj_train = cbind(levallois_nona[-unknown_sp,], pca_levallois_train$x)

levallois_proj = rbind(levallois_proj_train, unknown_proj)

## plot variances

pca_levallois_variance = summary(pca_levallois_train)

pc_var_data = t(pca_levallois_variance$importance[c(2,3),])

pc_var_data = cbind(1:nrow(pc_var_data), round(pc_var_data, 2) * 100)

pc_var_data <- as.data.frame(pc_var_data)

names(pc_var_data) <- c("PC", "Variance", "Cumulative")

ggplot(data = pc_var_data) +
   geom_path(mapping = aes(x = PC, y = Variance), colour="darkgrey") +
   geom_point(mapping = aes(x = PC, y = Variance)) +
   coord_cartesian(ylim=c(0,60),
                 xlim=c(1,8),
                 clip="off") +
   scale_x_continuous(breaks=c(1:8)) +
   labs(title="Principle Components", y = "% Variance") +
   annotate("text",
            x = pc_var_data$PC,
            y = -5,
            label = pc_var_data$Cumulative,
            size = 3) +
   annotate("text",
            x = 0.25,
            y = -5,
            label = "% Variance",
            size = 3) +
   theme_minimal() +
   theme(text = element_text(family="Times", size=12),
         plot.margin = margin(t = 1, r = 1, b = 1, l = 10, unit = "mm"),
         plot.title = element_text(face="bold",hjust=0.5,size=15),
         axis.title.x.bottom = element_text(margin=margin(t=5,r=1,b=1,l=1, unit ="mm")),
         axis.text.x = element_text(margin=margin(t=8,r=1,b=1,l=1, unit ="mm")))
ggsave(filename="./Images/pc_var_plot.pdf",
      device = "pdf")

nsites = length(unique(levallois_proj$Site))

unknown_sp <- which(levallois_proj$SpCode==2)

## change to factors for easy ggplo2 plotting

Site_levels = unique(levallois_proj[order(levallois_proj[,c("SpCode")]),"Site"])

Sp_levels = unique(levallois_proj[order(levallois_proj[,c("SpCode")]),"Sp"])

levallois_proj$Site = factor(levallois_proj$Site, levels=Site_levels)
levallois_proj$Sp = factor(levallois_proj$Sp, levels=Sp_levels)

p1 <- ggplot(data = levallois_proj,
        mapping = aes(Site, PC1, group = Site)) +
        geom_jitter(width = 0.15,
                      height = 0,
                      alpha = 0.5,
                      size = 0.5) +
        geom_boxplot(aes(colour = Sp, fill = Sp),
                    alpha = 0.8,
                    outlier.shape = NA) +
        theme_minimal() +
        theme(text = element_text(family="Times", size=12),
            plot.title = element_text(face="bold",hjust=0.5,size=15),
            axis.text.x = element_blank(),
            axis.title.x = element_blank())

p2 <- ggplot(data = levallois_proj,
        mapping = aes(Site, PC2, group = Site)) +
        geom_jitter(width = 0.15,
                      height = 0,
                      alpha = 0.5,
                      size = 0.5) +
        geom_boxplot(aes(colour = Sp, fill = Sp),
                    alpha = 0.8,
                    outlier.shape = NA) +
        theme_minimal() +
        theme(text = element_text(family="Times", size=12),
            plot.title = element_text(face="bold",hjust=0.5,size=15),
            axis.text.x = element_blank(),
            axis.title.x = element_blank())

p2

ggsave(filename="./Images/pca_boxplots_PC2.pdf",
     device = "pdf")

p3 <- ggplot(data = levallois_proj,
        mapping = aes(Site, PC3, group = Site)) +
        geom_jitter(width = 0.15,
                      height = 0,
                      alpha = 0.5,
                      size = 0.5) +
        geom_boxplot(aes(colour = Sp, fill = Sp),
                    alpha = 0.8,
                    outlier.shape = NA) +
        theme_minimal() +
        theme(text = element_text(family="Times", size=12),
            plot.title = element_text(face="bold",hjust=0.5,size=15),
            axis.text.x = element_text(size=8, angle=45, vjust=0.5),
            axis.title.x = element_blank())

#
fig <- ggarrange(p1,p2,p3,
            ncol=1,
            nrow=3,
            align="v")

annotate_figure(fig,
               top = text_grob("PCA Score Box Plots",
                                 family="Times",
                                 face="bold"),
               fig.lab.pos = "top")

ggsave(filename="./Images/pca_boxplots_PC123.pdf",
     device = "pdf")


#
ggplot(data = levallois_proj,
    mapping = aes(Site, PC2, group = Site)) +
    geom_jitter(width = 0.15,
                  height = 0,
                  alpha = 0.5,
                  size = 0.5) +
    geom_boxplot(aes(colour = Sp, fill = Sp),
                alpha = 0.8,
                outlier.shape = NA) +
    theme_minimal() +
    theme(text = element_text(family="Times", size=12),
        plot.title = element_text(face="bold",hjust=0.5,size=15),
        axis.text.x = element_text(size=12, angle=45, vjust=0.5),
        axis.title.x = element_blank())
ggsave(filename="./Images/pca_boxplots_PC2.pdf",
     device = "pdf",
     height = 10,
     width = 35,
     units = "cm")

## biplots
#biplots
my_density <- function (data, mapping, ...)
{
   ggplot(data = data, mapping=mapping) +
   stat_density_2d(aes(fill=Sp, alpha=stat(level)), colour=NA, geom="polygon")
}

ggpairs(data = subset(levallois_proj,SpCode != 2),
         columns=13:20,
         mapping=aes(colour=Sp,alpha=0.5),
         lower=list(continuous=wrap("points",size=0.01)),
         upper=list(continuous=my_density),
         legend=1) +
    scale_fill_manual(values=c("#F8766D", "#00BA38")) +
    scale_color_manual(values=c("#F8766D", "#00BA38")) +
   labs(title="PCA Pair Plots and Densities") +
   theme_minimal() +
   theme(text = element_text(family="Times", size=12),
         plot.title = element_text(face="bold",hjust=0.5,size=15))
ggsave(filename="./Images/pca_biplot_all.pdf",
      device = "pdf")

#
#with density
JKF1_hull_index <- chull(subset(levallois_proj,Site=="JKF-1")[,c("PC1","PC2")])
JKF1_hull_coords <- subset(levallois_proj,Site=="JKF-1")[JKF1_hull_index,c("PC1","PC2")]
JKF1_hull_centroid <- colMeans(JKF1_hull_coords)
JKF1_hull_centroid <- data.frame(PC1=JKF1_hull_centroid[1],PC2=JKF1_hull_centroid[2])

ALM3_hull_index <- chull(subset(levallois_proj,Site=="ALM-3")[,c("PC1","PC2")])
ALM3_hull_coords <- subset(levallois_proj,Site=="ALM-3")[ALM3_hull_index,c("PC1","PC2")]
ALM3_hull_centroid <- colMeans(ALM3_hull_coords)
ALM3_hull_centroid <- data.frame(PC1=ALM3_hull_centroid[1],PC2=ALM3_hull_centroid[2])


ggplot(data = subset(levallois_proj, SpCode != 2), aes(x = PC1, y = PC2)) +
   stat_density_2d(aes(fill=Sp, alpha=stat(level)),
                  geom="polygon") +
   geom_polygon(data=subset(levallois_proj,Site=="JKF-1")[JKF1_hull_index,c("PC1","PC2")],
               aes(x = PC1, y = PC2),
               fill=NA,
               colour="black") +
   geom_point(data=JKF1_hull_centroid,
               aes(x = PC1, y = PC2),
               shape=21,
               colour="black") +
   geom_polygon(data=subset(levallois_proj,Site=="ALM-3")[ALM3_hull_index,c("PC1","PC2")],
               aes(x = PC1, y = PC2),
               fill=NA,
               colour="blue") +
   geom_point(data=ALM3_hull_centroid,
               aes(x = PC1, y = PC2),
               shape=21,
               colour="blue") +
   scale_fill_manual(values=c("#F8766D", "#00BA38")) +
   scale_color_manual(values=c("#F8766D", "#00BA38")) +
   scale_x_continuous(breaks=c(-5:10)) +
   scale_y_continuous(breaks=c(-4:3)) +
   labs(title="PCA Scores") +
   theme_minimal() +
   theme(text = element_text(family="Times", size=12),
         plot.title = element_text(face="bold",hjust=0.5,size=15),
         legend.position = "top")

ggsave(filename="./Images/pca_12_JKF1_ALM3.pdf",
      device = "pdf")

JKF1_hull_index <- chull(subset(levallois_proj,Site=="JKF-1")[,c("PC3","PC2")])
JKF1_hull_coords <- subset(levallois_proj,Site=="JKF-1")[JKF1_hull_index,c("PC3","PC2")]
JKF1_hull_centroid <- colMeans(JKF1_hull_coords)
JKF1_hull_centroid <- data.frame(PC3=JKF1_hull_centroid[1],PC2=JKF1_hull_centroid[2])

ALM3_hull_index <- chull(subset(levallois_proj,Site=="ALM-3")[,c("PC3","PC2")])
ALM3_hull_coords <- subset(levallois_proj,Site=="ALM-3")[ALM3_hull_index,c("PC3","PC2")]
ALM3_hull_centroid <- colMeans(ALM3_hull_coords)
ALM3_hull_centroid <- data.frame(PC3=ALM3_hull_centroid[1],PC2=ALM3_hull_centroid[2])

ggplot(data = subset(levallois_proj, SpCode != 2), aes(x = PC3, y = PC2)) +
   stat_density_2d(aes(fill=Sp, alpha=stat(level)),
                  geom="polygon") +
   geom_polygon(data=subset(levallois_proj,Site=="JKF-1")[JKF1_hull_index,c("PC3","PC2")],
               aes(x = PC3, y = PC2),
               fill=NA,
               colour="black") +
   geom_point(data=JKF1_hull_centroid,
               aes(x = PC3, y = PC2),
               shape=21,
               colour="black") +
   geom_polygon(data=subset(levallois_proj,Site=="ALM-3")[ALM3_hull_index,c("PC2","PC3")],
               aes(x = PC3, y = PC2),
               fill=NA,
               colour="blue") +
   geom_point(data=ALM3_hull_centroid,
               aes(x = PC3, y = PC2),
               shape=21,
               colour="blue") +
   scale_fill_manual(values=c("#F8766D", "#00BA38")) +
   scale_color_manual(values=c("#F8766D", "#00BA38")) +
   scale_x_continuous(breaks=c(-5:10)) +
   scale_y_continuous(breaks=c(-4:3)) +
   labs(title="PCA Scores") +
   theme_minimal() +
   theme(text = element_text(family="Times", size=12),
         plot.title = element_text(face="bold",hjust=0.5,size=15),
         legend.position = "top")

ggsave(filename="./Images/pca_23_JKF1_ALM3.pdf",
      device = "pdf")

## how many to keep for classification

#collect AICs
AICs <- c()
xs <- c("PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8")
for(j in 1:8){
   f <- as.formula(paste("SpCode~",paste(xs[1:j],collapse="+")))
   logit_levallois <- glm(f,
                           data=levallois_proj[-unknown_sp,],
                           family=binomial(link="logit"))
   AICs <- c(AICs,logit_levallois$aic)
}

LogitAICs <- data.frame(PC=1:8,AIC=round(AICs,0))



#quick cross validation for the logit model to create a meaningful ROC curve
d <- levallois_proj[-unknown_sp,]
n <- nrow(d)
##repeat many times to get confidence envelope for the ROC curve
##the following code is inefficient, but the rocr ouput needs to be captured
##for use with ggplot instead of rocr's default plots
rocr_cv_perf <- data.frame(r=numeric(),tpr=numeric(),fpr=numeric())
rocr_cv_perf_auc <- data.frame(r=numeric(),tpr=numeric(),fpr=numeric())
for( j in 1:1000){
   random_sample_index <- base::sample(1:n,n/2)
   d_train <- d[random_sample_index,]
   d_cv <- d[-random_sample_index,]
   logit_levallois_train <- glm(SpCode~PC1+PC2+PC3+PC4,
                                 data=d_train,
                                 family=binomial(link="logit"))
   logit_levallois_cv_pred <- predict(logit_levallois_train,type="response",newdata=d_cv)
   rocr_pred <- prediction(logit_levallois_cv_pred,d_cv$SpCode)
   rocr_perf <- performance(rocr_pred,measure="tpr",x.measure="fpr")
   nn <- length(rocr_perf@x.values[[1]])
   rocr_cv_perf <- rbind(rocr_cv_perf,data.frame(r=rep(j,nn),tpr=rocr_perf@y.values[[1]],fpr=rocr_perf@x.values[[1]]))

   rocr_perf <- performance(rocr_pred,measure="auc")
   nn <- length(rocr_perf@y.values[[1]])
   rocr_cv_perf_auc <- rbind(rocr_cv_perf_auc,data.frame(r=rep(j,nn),auc=rocr_perf@y.values[[1]]))
}

#plotting multiple ROC curves from CV analysis
ggplot(data = rocr_cv_perf,
         aes(y=tpr,x=fpr,group=r)) +
   geom_line(alpha=0.01) +
   geom_line(data=data.frame(x=seq(0,1,0.001),y=seq(0,1,0.001)),
            aes(x=x,y=y),
            linetype=2,
            colour="grey",
            inherit.aes=F) +
   labs(title="ROC Curves from Logit Cross Validation",
         y="TPR",
         x="FPR") +
   theme_minimal() +
   theme(text = element_text(family="Times", size=12),
         plot.title = element_text(face="bold",hjust=0.5,size=15))
ggsave(filename="./Images/logit_cv_roc.pdf",
      device = "pdf")

##
#AUC histogram
n <- length(rocr_cv_perf_auc$auc)
nbins <- 1 + (3.222 * log(n))
ggplot(data = data.frame(AUC=rocr_cv_perf_auc$auc),
            mapping = aes(x = AUC, stat(density))) +
      geom_histogram(bins=nbins,
                     color="white") +
      labs(x="AUC",
            y="Density",
            title="AUC from Logit Cross Validation") +
      theme_minimal() +
      theme(text = element_text(family="Times", size=12),
            plot.title = element_text(face="bold",hjust=0.5,size=15))

ggsave(filename="./Images/auc_distribution.pdf",
      device = "pdf")

## finally run the real thing...

logit_levallois <- glm(SpCode~PC1+PC2+PC3+PC4,
                        data=levallois_proj[-unknown_sp,],
                        family=binomial(link="logit"))

logit_predict_JKF1 <- predict(logit_levallois,
    newdata=levallois_proj[which(levallois_proj$Site=="JKF-1"),],
    type="response",
    se.fit=T)

summary(logit_predict_JKF1$fit)

logit_predict_ALM3 <- predict(logit_levallois,
    newdata=levallois_proj[which(levallois_proj$Site=="ALM-3"),],
    type="response",
    se.fit=T)

summary(logit_predict_ALM3$fit)
